package senai.fatesg.com.cgponto.model;

public enum MotivoAbono {

    /**
     * MOTIVOS DE ABONO
     * Codigo	Descricao
     * 001	AUSENCIA JUSTIFICADA
     * 002	HORAS JUSTIFICADAS
     * 003	ATESTADO MEDICO
     * 004	LICENCA CASAMENTO
     * 005	LICENCA PATERNIDADE
     * 006	LICENCA MATERNIDADE
     * 007	LICENCA AMAMENTACAO
     * 008	SERVICO EXTERNO
     * 009	FOLGA
     * 010	ACIDENTE DE TRABALHO
     * 011	SAIDA AUTORIZADA
     * 012	COMPENSACAO
     * 013	ATESTADO DOACAO SANGUE
     * 014	ESQUECIMENTO
     */

    AUSENCIA_JUSTIFICADA("AUSÊNCIA JUSTIFICADA"),
    HORAS_JUSTIFICADAS("HORAS JUSTIFICADAS"),
    ATESTADO_MEDICO("ATESTADO MÉDICO"),
    LICENCA_CASAMENTO("LICENÇA CASAMENTO"),
    LICENCA_PATERNIDADE("LICENÇA PATERNIDADE"),
    LICENCA_MATERINIDADE("LICENÇA MATERNIDADE"),
    LICENCA_AMAMENTACAO("LICENÇA AMAMENTAÇÃO"),
    SERVICO_EXTERNO("SERVIÇO EXTERNO"),
    FOLGA("FOLGA"),
    ACIDENTE_TRABALHO("ACIDENTE DE TRABALHO"),
    SAIDA_AUTORIZADA("SAÍDA AUTORIZADA"),
    COMPENSACAO("COMPENSAÇÃO"),
    ATESTADO_DOACAO_SANGUE("ATESTADO DOAÇÃO DE SANGUE"),
    ESQUECIMENTO("ESQUECIMENTO");


    private String descricao;

    MotivoAbono(String descricao){
        this.descricao = descricao;
    }

    public String getDescricao(){
        return descricao;
    }
}
